#+TITLE: BB Task Completion

Created to toy with zsh completion for bb's new tasks feature.

* Resources:

[[https://github.com/babashka/babashka/issues/778][BB Tasks spec/issue]]

bb.edn examples:

- [[https://github.com/borkdude/antq/blob/bb-run/bb.edn][Antq bb.edn example]] (copied into the ~bb.edn~ in this repo)

Zsh completion help:

- [[https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org][Zsh completion script guide]] - this guide in particular is very useful!
- [[https://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html][Zsh completion blog post]]

* Zsh autocompletion
Something like the following is typical to get zsh completion working (see the
first few paragraphs [[https://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html][here]] for reference):

#+begin_src zsh
# add completion files to fpath
fpath=(~/.zsh/completion $fpath)

# initialize completion system
autoload -Uz compinit && compinit -i
#+end_src

* BB task completion
Completion for bb requires a zsh file in ~/.zsh/completion/_bb~ (or wherever you
append your ~fpath~).

See ~./_bb~ and ~./bb_task_completion.clj~ for a working implementation.

** Installation

This repo was implemented as a proof of concept, and is not at all intended as a
final product for bb-based completion. However if you want to try it, something
like this could work as a manual install process.

#+begin_src sh
# clone this repo to ~/russmatney/bb-task-completion
ln -s ~/russmatney/bb-task-completion/bb_task_completion.clj ~/.zsh/bb_task_completion.clj
ln -s ~/russmatney/bb-task-completion/_bb ~/.zsh/completion/_bb
#+end_src

* Open questions
- What's the expected installation process for bb users?

  We can probably get people to add a `source <(some-bb-command)` line to do the
  work

- Where should the ~bb_task_completion.clj~ script/logic live?
  Right now the task uses a hard-coded helper script to parse the bb.edn and
  format a string. Maybe this should live somewhere in the babashka repo itself?

  As implemented, users will need to install two scripts, which is not ideal.

* Next steps

- Completion for the rest of the bb cli options?
